spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/camp
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    session:
      timeout: 30m

jwt:
  secret:
    key: eoguddleoguddleoguddleoguddleoguddleoguddleoguddleoguddleoguddleoguddleoguddleoguddleoguddleoguddleoguddleoguddleoguddleoguddl